#!/usr/bin/env python3
# =============================================================================
# File:        grabber/grabber_node.py
# Package:     articubot_one (standalone script, no colcon build step needed)
# Platform:    Raspberry Pi 4 (shyam-rpi4) / Ubuntu 22.04 / ROS 2 Humble
# =============================================================================
# DESCRIPTION
# -----------
# Drives the front grabber's MG90S servo straight from the Pi 4's hardware
# PWM on GPIO 18 (physical pin 12). No PCA9685, no I2C: the pulse train is
# generated by the PWM peripheral itself, so it is jitter-free and costs no
# CPU, and it leaves the I2C bus entirely to the thermal camera.
#
# INTERFACES
# ----------
#   /grabber/open    std_srvs/Trigger   swing to open_deg
#   /grabber/close   std_srvs/Trigger   swing to closed_deg
#   /grabber/angle   std_msgs/Float32   go to any angle (degrees); use this
#                                       to find open_deg / closed_deg
#   /grabber/state   std_msgs/Float32   current commanded angle, 2 Hz
#
# Moves are stepped (step_deg every step_delay_s) instead of jumping, so the
# servo never pulls a big current spike through the 5 V supply. After
# idle_release_s with no new command the pulses stop and the servo goes
# limp, so it doesn't sit buzzing and heating against a hard stop. Set
# idle_release_s to 0 to hold position instead (e.g. while carrying).
#
# HARDWARE SETUP (once)
# ---------------------
#   /boot/firmware/config.txt:   dtoverlay=pwm,pin=18,func=2
#   udev rule so this runs without sudo: grabber/99-robot-pwm.rules
#   Wiring: Pi pin 12 (GPIO 18) -> servo signal (orange)
#           servo red  -> 5 V from the buck converter, NOT the Pi
#           servo brown -> buck GND, and buck GND joined to a Pi GND pin
#
# The PWM appears as /sys/class/pwm/pwmchip<N>/pwm<channel>; GPIO 18 is
# channel 0. Check the chip number with `ls /sys/class/pwm`.
#
# If the PWM files can't be opened the node still runs in simulated mode
# (everything works, nothing moves), and says so in its log.
#
# PARAMETERS
# ----------
#   pwm_chip (0) pwm_channel (0)
#   min_pulse_us (500) max_pulse_us (2500) range_deg (180)
#   open_deg (110.0) closed_deg (30.0)      placeholders: calibrate these
#   step_deg (2.0) step_delay_s (0.02)      slew rate
#   idle_release_s (1.0)                    0 = hold position
#
# RUN
# ---
#   python3 ~/robot_ws/src/articubot_one/grabber/grabber_node.py
#   ros2 service call /grabber/open std_srvs/srv/Trigger
#   ros2 topic pub --once /grabber/angle std_msgs/msg/Float32 "{data: 90.0}"
# =============================================================================

import os
import threading
import time

import rclpy
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.executors import MultiThreadedExecutor
from rclpy.node import Node
from std_msgs.msg import Float32
from std_srvs.srv import Trigger

PERIOD_NS = 20_000_000  # 50 Hz, standard for hobby servos


class SysfsPwm:
    """One hardware PWM channel through the kernel's sysfs interface."""

    def __init__(self, chip, channel, logger):
        self.base = f'/sys/class/pwm/pwmchip{chip}'
        self.path = f'{self.base}/pwm{channel}'
        self.available = False
        try:
            if not os.path.isdir(self.path):
                self._write(f'{self.base}/export', channel)
            # udev needs a moment to fix permissions on freshly exported files
            for _ in range(60):
                if os.access(f'{self.path}/period', os.W_OK):
                    break
                time.sleep(0.05)
            # Duty must never exceed period, so zero duty before setting period.
            self._write(f'{self.path}/duty_cycle', 0)
            self._write(f'{self.path}/period', PERIOD_NS)
            self._write(f'{self.path}/enable', 1)
            self.available = True
            logger.info(f'Hardware PWM ready at {self.path} (50 Hz).')
        except OSError as exc:
            logger.warning(f'Hardware PWM unavailable ({exc}). Running in simulated mode; '
                           'the servo will not move. See the setup notes in this file.')

    @staticmethod
    def _write(path, value):
        with open(path, 'w') as handle:
            handle.write(str(int(value)))

    def pulse_us(self, microseconds):
        if self.available:
            self._write(f'{self.path}/duty_cycle', int(microseconds * 1000))

    def release(self):
        if self.available:
            self._write(f'{self.path}/duty_cycle', 0)

    def close(self):
        if self.available:
            try:
                self._write(f'{self.path}/duty_cycle', 0)
                self._write(f'{self.path}/enable', 0)
            except OSError:
                pass


class GrabberNode(Node):

    def __init__(self):
        super().__init__('grabber')
        p = self.declare_parameter
        self.min_us = p('min_pulse_us', 500).value
        self.max_us = p('max_pulse_us', 2500).value
        self.range_deg = p('range_deg', 180.0).value
        self.open_deg = p('open_deg', 110.0).value
        self.closed_deg = p('closed_deg', 30.0).value
        self.step_deg = max(0.1, p('step_deg', 2.0).value)
        self.step_delay = max(0.0, p('step_delay_s', 0.02).value)
        self.idle_release = p('idle_release_s', 1.0).value

        self.pwm = SysfsPwm(p('pwm_chip', 0).value, p('pwm_channel', 0).value, self.get_logger())
        self._lock = threading.Lock()
        self._release_timer = None
        self.angle = None  # unknown until the first move

        group = ReentrantCallbackGroup()
        self.create_service(Trigger, '/grabber/open', self._srv_open, callback_group=group)
        self.create_service(Trigger, '/grabber/close', self._srv_close, callback_group=group)
        self.create_subscription(Float32, '/grabber/angle', self._on_angle, 10,
                                 callback_group=group)
        self.state_pub = self.create_publisher(Float32, '/grabber/state', 10)
        self.create_timer(0.5, self._publish_state, callback_group=group)
        self.get_logger().info(f'Grabber ready: open {self.open_deg} deg, '
                               f'closed {self.closed_deg} deg.')

    # -- motion ------------------------------------------------------------

    def _pulse_for(self, angle):
        angle = max(0.0, min(self.range_deg, angle))
        return self.min_us + (self.max_us - self.min_us) * angle / self.range_deg

    def move_to(self, target):
        target = max(0.0, min(self.range_deg, float(target)))
        with self._lock:
            if self._release_timer is not None:
                self._release_timer.cancel()
            start = target if self.angle is None else self.angle  # first move: go direct
            steps = max(1, int(abs(target - start) / self.step_deg + 0.999))
            for i in range(1, steps + 1):
                angle = start + (target - start) * i / steps
                self.pwm.pulse_us(self._pulse_for(angle))
                self.angle = angle
                if self.step_delay > 0.0:
                    time.sleep(self.step_delay)
            if self.idle_release > 0.0:
                self._release_timer = threading.Timer(self.idle_release, self.pwm.release)
                self._release_timer.daemon = True
                self._release_timer.start()

    # -- interfaces --------------------------------------------------------

    def _srv_open(self, _request, response):
        self.move_to(self.open_deg)
        response.success, response.message = True, f'Open ({self.open_deg:.0f} deg).'
        return response

    def _srv_close(self, _request, response):
        self.move_to(self.closed_deg)
        response.success, response.message = True, f'Closed ({self.closed_deg:.0f} deg).'
        return response

    def _on_angle(self, msg):
        self.get_logger().info(f'Moving to {msg.data:.1f} deg.')
        self.move_to(msg.data)

    def _publish_state(self):
        if self.angle is not None:
            self.state_pub.publish(Float32(data=float(self.angle)))

    def destroy_node(self):
        if self._release_timer is not None:
            self._release_timer.cancel()
        self.pwm.close()
        return super().destroy_node()


def main():
    rclpy.init()
    node = GrabberNode()
    executor = MultiThreadedExecutor(num_threads=3)
    executor.add_node(node)
    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == '__main__':
    main()